Feature/initialize/add component modal
SEIZENSETSU/fleet-tracker-flutter pull request #21
Opened 2024-06-28 16:30 UTC by ishibashikeita

## 概要
基本となるモーダルと開発用のモーダルを作成

## 変更点
開発用設定から一時的にエリア内・外を切り替えられるボタンを設置

2024-06-28 16:31 UTC, ishibashikeita commented
authを実装する前にdevから切ったのでちょっと小さめですがプルリク出します

2024-06-29 00:33 UTC, kakeru-ikeda requested changes
レビュー行いました。
修正は6/29 23:59までにお願いします。

2024-06-29 00:33 UTC, kakeru-ikeda commented on lib/View/Component/CustomWidget/Modal/custom_modal.dart
> +    bool? expand = true,
初期値入る変数は特例なければnull許容外せます

2024-06-29 00:33 UTC, kakeru-ikeda commented on lib/View/Component/CustomWidget/Modal/custom_modal.dart
> +                    child: Row(
単一childrenのRowは避けましょう（Rowウィジェットの意に反するため）
子要素追加の予定がある場合は無視してください

2024-06-29 00:33 UTC, kakeru-ikeda commented on lib/View/Component/CustomWidget/Modal/custom_modal.dart
> +                                  fontWeight: FontWeight.normal,
文字列×は依存性と可読性ともによくないのでアイコンにしてください

2024-06-29 00:33 UTC, kakeru-ikeda commented on lib/View/Setting/setting_top_view.dart
> +              },
![image](https://github.com/SEIZENSETSU/fleet-tracker-flutter/assets/93127331/40bb95fa-79ae-443d-8128-6447ca12133c)
セルの実装を見返しましたが、onTap()のnullチェックだけで判定効きそうです。
isTappedフィールドは削除してください。

2024-06-29 03:35 UTC, kakeru-ikeda commented
承認👍

2024-06-29 03:35 UTC, merged