Feature/local notifications
SEIZENSETSU/fleet-tracker-flutter pull request #28
Opened 2024-06-30 11:56 UTC by ryou3chi

## 概要
このセクションでは、このPRの目的と概要を簡潔に説明してください。
ローカル通知の実装

## 変更点
このセクションでは、具体的な変更点や修正箇所を箇条書きでリストアップしてください。

・local notifications serviceの追加

## 確認事項
- https://www.notion.so/5eb3b2157e6c453c9556022bfe04fdda

2024-06-30 12:55 UTC, kakeru-ikeda reviewed
レビュー完了しました👀
変更は2024/07/01 18:00までにお願いします

2024-06-30 12:55 UTC, kakeru-ikeda commented on lib/Service/Package/local_notification/local_notifications_service.dart
ディレクトリ名は大文字スタートのキャメルケースでお願いします。

2024-06-30 12:55 UTC, kakeru-ikeda commented on lib/Service/Package/local_notification/local_notifications_service.dart
> +import 'package:flutter/widgets.dart';
Widgetは見当たりませんでした
利用予定がない場合は消してください

2024-06-30 12:55 UTC, kakeru-ikeda commented on lib/Service/Package/local_notification/local_notifications_service.dart
> +  ///通知バーの設定
細かいですが）
コメントの記載方法はできるだけ他のサービスに倣ってほしいです。
///後は半角スペース開け、引数は[]指定後半角スペース開け
```dart
/// 通知バーの設定
/// [title] 通知のタイトル
/// [body] 通知の内容
```

2024-06-30 12:57 UTC, kakeru-ikeda commented
（以降）Messagingのコミットメッセージでのtypoが目立ちます。
本サービス実装時に気をつけてください

2024-07-01 07:47 UTC, ryou3chi commented
修正しました

2024-07-01 07:59 UTC, kakeru-ikeda requested changes
修正お願いします
本日18時まで

2024-07-01 07:59 UTC, kakeru-ikeda commented on lib/Service/Package/LocalNotification/local_notifications_service.dart
>    ///【title】通知のタイトル
https://github.com/SEIZENSETSU/fleet-tracker-flutter/pull/28#discussion_r1660173959
「引数は[]指定後半角スペース開け」
すいませんがお願いします🥺

2024-07-01 08:16 UTC, ryou3chi commented
ごめん…

2024-07-01 08:25 UTC, kakeru-ikeda requested changes
もう一度お願いします

2024-07-01 08:25 UTC, kakeru-ikeda commented on lib/Service/Package/LocalNotification/local_notifications_service.dart
> +  /// 【title】通知のタイトル
【】-> []
https://github.com/SEIZENSETSU/fleet-tracker-flutter/pull/28#discussion_r1660173959
```dart
/// 通知バーの設定
/// [title] 通知のタイトル
/// [body] 通知の内容
```
上記コメントアウトをコピーしていただけますと間違いないかと思います

2024-07-01 08:28 UTC, ryou3chi commented
ほんとすまん

2024-07-01 08:39 UTC, merged